"""Add config column to assets

Revision ID: 2e8ce4b77d7c
Revises: 77f226e884dd
Create Date: 2025-12-21 00:04:36.791428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8ce4b77d7c'
down_revision: Union[str, Sequence[str], None] = '77f226e884dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('config', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'pipelines', 'pipeline_versions', ['published_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.drop_column('assets', 'config')
    # ### end Alembic commands ###
