"""add_server_defaults_to_pipeline_run_context

Revision ID: 3b6b887bdcb6
Revises: 359d29adc504
Create Date: 2025-12-28 12:16:29.446017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b6b887bdcb6'
down_revision: Union[str, Sequence[str], None] = '359d29adc504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_run_context', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=False)
    op.alter_column('pipeline_run_context', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=False)
    op.alter_column('pipeline_run_context', 'environment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default='{}',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_run_context', 'environment',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_run_context', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('pipeline_run_context', 'context',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
