"""Removed unused connectors

Revision ID: 3fba53aeb1fa
Revises: 53a1f298f9b8
Create Date: 2025-12-24 05:24:51.813328

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3fba53aeb1fa'
down_revision: Union[str, Sequence[str], None] = '53a1f298f9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
