"""add_max_retries_to_pipelines

Revision ID: 55ea689a1bfb
Revises: 3fba53aeb1fa
Create Date: 2025-12-24 06:11:34.740476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ea689a1bfb'
down_revision: Union[str, Sequence[str], None] = '3fba53aeb1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('pipelines', sa.Column('max_retries', sa.Integer(), nullable=True))
    # Update existing rows
    op.execute("UPDATE pipelines SET max_retries = 3")
    # Make it NOT NULL
    op.alter_column('pipelines', 'max_retries', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'max_retries')
    # ### end Alembic commands ###
