"""Reinitialized Schema

Revision ID: 77f226e884dd
Revises: 
Create Date: 2025-12-16 17:43:34.577585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f226e884dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('JOB_FAILURE', 'JOB_SUCCESS', 'DATA_QUALITY_FAILURE', 'SCHEMA_CHANGE_DETECTED', 'SLA_BREACH', 'MANUAL', name='alerttype'), nullable=False),
    sa.Column('delivery_method', sa.Enum('EMAIL', 'SLACK', 'WEBHOOK', 'PAGERDUTY', 'IN_APP', name='alertdeliverymethod'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('threshold_window_minutes', sa.Integer(), nullable=True),
    sa.Column('pipeline_filter', sa.JSON(), nullable=True),
    sa.Column('severity_filter', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_config_enabled', 'alert_configs', ['enabled', 'alert_type'], unique=False)
    op.create_index(op.f('ix_alert_configs_created_at'), 'alert_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_configs_created_by'), 'alert_configs', ['created_by'], unique=False)
    op.create_index(op.f('ix_alert_configs_deleted_at'), 'alert_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alert_configs_enabled'), 'alert_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_alert_configs_name'), 'alert_configs', ['name'], unique=False)
    op.create_index(op.f('ix_alert_configs_user_id'), 'alert_configs', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=8), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_created_by'), 'api_keys', ['created_by'], unique=False)
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.Enum('POSTGRESQL', 'MYSQL', 'MARIADB', 'MSSQL', 'ORACLE', 'SQLITE', 'MONGODB', 'REDIS', 'ELASTICSEARCH', 'CASSANDRA', 'DYNAMODB', 'SNOWFLAKE', 'BIGQUERY', 'REDSHIFT', 'DATABRICKS', 'LOCAL_FILE', 'S3', 'GCS', 'AZURE_BLOB', 'FTP', 'SFTP', 'REST_API', 'GRAPHQL', 'KAFKA', 'RABBITMQ', 'GOOGLE_SHEETS', 'AIRTABLE', 'SALESFORCE', 'HUBSPOT', 'STRIPE', 'CUSTOM_SCRIPT', 'SINGER_TAP', name='connectortype'), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_schema_discovery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('max_concurrent_connections', sa.Integer(), nullable=False),
    sa.Column('connection_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_created_at'), 'connections', ['created_at'], unique=False)
    op.create_index(op.f('ix_connections_created_by'), 'connections', ['created_by'], unique=False)
    op.create_index(op.f('ix_connections_deleted_at'), 'connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=False)
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_timezone', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED', 'BROKEN', name='pipelinestatus'), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('published_version_id', sa.Integer(), nullable=True),
    sa.Column('max_parallel_runs', sa.Integer(), nullable=False),
    sa.Column('execution_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_parallel_runs > 0', name='ck_pipeline_max_parallel'),
    sa.CheckConstraint('priority BETWEEN 1 AND 10', name='ck_pipeline_priority'),
    sa.ForeignKeyConstraint(['published_version_id'], ['pipeline_versions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_schedule', 'pipelines', ['schedule_enabled', 'schedule_cron'], unique=False)
    op.create_index(op.f('ix_pipelines_created_at'), 'pipelines', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipelines_created_by'), 'pipelines', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipelines_deleted_at'), 'pipelines', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=False)
    op.create_index(op.f('ix_pipelines_user_id'), 'pipelines', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('fully_qualified_name', sa.String(length=500), nullable=True),
    sa.Column('is_source', sa.Boolean(), nullable=False),
    sa.Column('is_destination', sa.Boolean(), nullable=False),
    sa.Column('is_incremental_capable', sa.Boolean(), nullable=False),
    sa.Column('schema_metadata', sa.JSON(), nullable=True),
    sa.Column('current_schema_version', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('row_count_estimate', sa.Integer(), nullable=True),
    sa.Column('size_bytes_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('is_source = TRUE OR is_destination = TRUE', name='ck_asset_direction'),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'name', name='uq_asset_name_per_connection')
    )
    op.create_index('idx_asset_source_dest', 'assets', ['is_source', 'is_destination'], unique=False)
    op.create_index(op.f('ix_assets_connection_id'), 'assets', ['connection_id'], unique=False)
    op.create_index(op.f('ix_assets_created_at'), 'assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_assets_created_by'), 'assets', ['created_by'], unique=False)
    op.create_index(op.f('ix_assets_deleted_at'), 'assets', ['deleted_at'], unique=False)
    op.create_table('pipeline_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'version', name='uq_pipeline_version')
    )
    op.create_index('idx_version_published', 'pipeline_versions', ['pipeline_id', 'is_published'], unique=False)
    op.create_index(op.f('ix_pipeline_versions_created_at'), 'pipeline_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_versions_created_by'), 'pipeline_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_versions_pipeline_id'), 'pipeline_versions', ['pipeline_id'], unique=False)
    op.create_table('scheduler_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sceduler_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduler_event_type_time', 'scheduler_events', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_scheduler_pipeline_time', 'scheduler_events', ['pipeline_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_scheduler_events_created_at'), 'scheduler_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduler_events_created_by'), 'scheduler_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_scheduler_events_pipeline_id'), 'scheduler_events', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_scheduler_events_timestamp'), 'scheduler_events', ['timestamp'], unique=False)
    op.create_table('asset_schema_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('json_schema', sa.JSON(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('change_summary', sa.JSON(), nullable=True),
    sa.Column('is_breaking_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version', name='uq_asset_schema_version')
    )
    op.create_index('idx_schema_version_discovered', 'asset_schema_versions', ['asset_id', 'discovered_at'], unique=False)
    op.create_index(op.f('ix_asset_schema_versions_asset_id'), 'asset_schema_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_schema_versions_created_at'), 'asset_schema_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_schema_versions_created_by'), 'asset_schema_versions', ['created_by'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version_id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_strategy', sa.Enum('NONE', 'FIXED', 'EXPONENTIAL_BACKOFF', 'LINEAR_BACKOFF', name='retrystrategy'), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('infra_error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('queue_name', sa.String(length=255), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_correlation', 'jobs', ['correlation_id'], unique=False)
    op.create_index('idx_job_pipeline_status', 'jobs', ['pipeline_id', 'status'], unique=False)
    op.create_index('idx_job_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_pipeline_id'), 'jobs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('pipeline_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operator_type', sa.Enum('EXTRACT', 'TRANSFORM', 'LOAD', 'VALIDATE', 'NOOP', 'MERGE', 'UNION', 'JOIN', name='operatortype'), nullable=False),
    sa.Column('operator_class', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=True),
    sa.Column('destination_asset_id', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['destination_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipeline_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_version_id', 'node_id', name='uq_node_id_per_version')
    )
    op.create_index('idx_node_assets', 'pipeline_nodes', ['source_asset_id', 'destination_asset_id'], unique=False)
    op.create_index('idx_node_operator_type', 'pipeline_nodes', ['operator_type'], unique=False)
    op.create_index(op.f('ix_pipeline_nodes_created_at'), 'pipeline_nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_nodes_created_by'), 'pipeline_nodes', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_nodes_pipeline_version_id'), 'pipeline_nodes', ['pipeline_version_id'], unique=False)
    op.create_table('watermarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('last_value', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('watermark_column', sa.String(length=255), nullable=True),
    sa.Column('watermark_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'asset_id', name='uq_watermark_pipeline_asset')
    )
    op.create_index('idx_watermark_updated', 'watermarks', ['last_updated'], unique=False)
    op.create_index(op.f('ix_watermarks_asset_id'), 'watermarks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_watermarks_created_at'), 'watermarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_watermarks_created_by'), 'watermarks', ['created_by'], unique=False)
    op.create_index(op.f('ix_watermarks_pipeline_id'), 'watermarks', ['pipeline_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_config_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'CRITICAL', name='alertlevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', 'ACKNOWLEDGED', 'SKIPPED', name='alertstatus'), nullable=False),
    sa.Column('delivery_method', sa.Enum('EMAIL', 'SLACK', 'WEBHOOK', 'PAGERDUTY', 'IN_APP', name='alertdeliverymethod'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_level_status', 'alerts', ['level', 'status'], unique=False)
    op.create_index('idx_alert_pipeline_created', 'alerts', ['pipeline_id', 'created_at'], unique=False)
    op.create_index('idx_alert_status_created', 'alerts', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_alert_config_id'), 'alerts', ['alert_config_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_created_by'), 'alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_alerts_job_id'), 'alerts', ['job_id'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_index(op.f('ix_alerts_pipeline_id'), 'alerts', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_log_level_time', 'job_logs', ['job_id', 'level', 'timestamp'], unique=False)
    op.create_index(op.f('ix_job_logs_created_at'), 'job_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_logs_created_by'), 'job_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_level'), 'job_logs', ['level'], unique=False)
    op.create_index(op.f('ix_job_logs_timestamp'), 'job_logs', ['timestamp'], unique=False)
    op.create_table('pipeline_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version_id', sa.Integer(), nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('from_node_id != to_node_id', name='ck_edge_no_self_loop'),
    sa.ForeignKeyConstraint(['from_node_id'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipeline_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_version_id', 'from_node_id', 'to_node_id', name='uq_edge_unique')
    )
    op.create_index('idx_edge_from', 'pipeline_edges', ['from_node_id'], unique=False)
    op.create_index('idx_edge_to', 'pipeline_edges', ['to_node_id'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_created_at'), 'pipeline_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_created_by'), 'pipeline_edges', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_edges_pipeline_version_id'), 'pipeline_edges', ['pipeline_version_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_version_id', sa.Integer(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIALIZING', 'RUNNING', 'COMPLETED', 'PARTIAL_SUCCESS', 'FAILED', 'CANCELLED', 'SKIPPED', name='pipelinerunstatus'), nullable=False),
    sa.Column('total_extracted', sa.Integer(), nullable=False),
    sa.Column('total_loaded', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('bytes_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_step_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_version_id'], ['pipeline_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'run_number', name='uq_pipeline_run_number')
    )
    op.create_index('idx_run_pipeline_created', 'pipeline_runs', ['pipeline_id', 'created_at'], unique=False)
    op.create_index('idx_run_status_started', 'pipeline_runs', ['status', 'started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_created_by'), 'pipeline_runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_job_id'), 'pipeline_runs', ['job_id'], unique=True)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_started_at'), 'pipeline_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('pipeline_run_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_run_context_created_at'), 'pipeline_run_context', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_run_context_created_by'), 'pipeline_run_context', ['created_by'], unique=False)
    op.create_index(op.f('ix_pipeline_run_context_pipeline_run_id'), 'pipeline_run_context', ['pipeline_run_id'], unique=True)
    op.create_table('step_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('operator_type', sa.Enum('EXTRACT', 'TRANSFORM', 'LOAD', 'VALIDATE', 'NOOP', 'MERGE', 'UNION', 'JOIN', name='operatortype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'WARNING', 'FAILED', 'SKIPPED', name='operatorrunstatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('records_in', sa.Integer(), nullable=False),
    sa.Column('records_out', sa.Integer(), nullable=False),
    sa.Column('records_filtered', sa.Integer(), nullable=False),
    sa.Column('records_error', sa.Integer(), nullable=False),
    sa.Column('bytes_processed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['pipeline_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_run_node', 'step_runs', ['node_id', 'status'], unique=False)
    op.create_index('idx_step_run_status', 'step_runs', ['pipeline_run_id', 'status'], unique=False)
    op.create_index(op.f('ix_step_runs_created_at'), 'step_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_step_runs_created_by'), 'step_runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_step_runs_pipeline_run_id'), 'step_runs', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_step_runs_status'), 'step_runs', ['status'], unique=False)
    op.create_table('step_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_run_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['step_run_id'], ['step_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_log_level_time', 'step_logs', ['step_run_id', 'level', 'timestamp'], unique=False)
    op.create_index(op.f('ix_step_logs_created_at'), 'step_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_step_logs_created_by'), 'step_logs', ['created_by'], unique=False)
    op.create_index(op.f('ix_step_logs_level'), 'step_logs', ['level'], unique=False)
    op.create_index(op.f('ix_step_logs_step_run_id'), 'step_logs', ['step_run_id'], unique=False)
    op.create_index(op.f('ix_step_logs_timestamp'), 'step_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_logs_timestamp'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_step_run_id'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_level'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_created_by'), table_name='step_logs')
    op.drop_index(op.f('ix_step_logs_created_at'), table_name='step_logs')
    op.drop_index('idx_step_log_level_time', table_name='step_logs')
    op.drop_table('step_logs')
    op.drop_index(op.f('ix_step_runs_status'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_pipeline_run_id'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_created_by'), table_name='step_runs')
    op.drop_index(op.f('ix_step_runs_created_at'), table_name='step_runs')
    op.drop_index('idx_step_run_status', table_name='step_runs')
    op.drop_index('idx_step_run_node', table_name='step_runs')
    op.drop_table('step_runs')
    op.drop_index(op.f('ix_pipeline_run_context_pipeline_run_id'), table_name='pipeline_run_context')
    op.drop_index(op.f('ix_pipeline_run_context_created_by'), table_name='pipeline_run_context')
    op.drop_index(op.f('ix_pipeline_run_context_created_at'), table_name='pipeline_run_context')
    op.drop_table('pipeline_run_context')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_started_at'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_job_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_by'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_index('idx_run_status_started', table_name='pipeline_runs')
    op.drop_index('idx_run_pipeline_created', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_edges_pipeline_version_id'), table_name='pipeline_edges')
    op.drop_index(op.f('ix_pipeline_edges_created_by'), table_name='pipeline_edges')
    op.drop_index(op.f('ix_pipeline_edges_created_at'), table_name='pipeline_edges')
    op.drop_index('idx_edge_to', table_name='pipeline_edges')
    op.drop_index('idx_edge_from', table_name='pipeline_edges')
    op.drop_table('pipeline_edges')
    op.drop_index(op.f('ix_job_logs_timestamp'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_level'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_created_by'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_created_at'), table_name='job_logs')
    op.drop_index('idx_job_log_level_time', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_pipeline_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_job_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_by'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_config_id'), table_name='alerts')
    op.drop_index('idx_alert_status_created', table_name='alerts')
    op.drop_index('idx_alert_pipeline_created', table_name='alerts')
    op.drop_index('idx_alert_level_status', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_watermarks_pipeline_id'), table_name='watermarks')
    op.drop_index(op.f('ix_watermarks_created_by'), table_name='watermarks')
    op.drop_index(op.f('ix_watermarks_created_at'), table_name='watermarks')
    op.drop_index(op.f('ix_watermarks_asset_id'), table_name='watermarks')
    op.drop_index('idx_watermark_updated', table_name='watermarks')
    op.drop_table('watermarks')
    op.drop_index(op.f('ix_pipeline_nodes_pipeline_version_id'), table_name='pipeline_nodes')
    op.drop_index(op.f('ix_pipeline_nodes_created_by'), table_name='pipeline_nodes')
    op.drop_index(op.f('ix_pipeline_nodes_created_at'), table_name='pipeline_nodes')
    op.drop_index('idx_node_operator_type', table_name='pipeline_nodes')
    op.drop_index('idx_node_assets', table_name='pipeline_nodes')
    op.drop_table('pipeline_nodes')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_pipeline_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_correlation_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_index('idx_job_status_created', table_name='jobs')
    op.drop_index('idx_job_pipeline_status', table_name='jobs')
    op.drop_index('idx_job_correlation', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_asset_schema_versions_created_by'), table_name='asset_schema_versions')
    op.drop_index(op.f('ix_asset_schema_versions_created_at'), table_name='asset_schema_versions')
    op.drop_index(op.f('ix_asset_schema_versions_asset_id'), table_name='asset_schema_versions')
    op.drop_index('idx_schema_version_discovered', table_name='asset_schema_versions')
    op.drop_table('asset_schema_versions')
    op.drop_index(op.f('ix_scheduler_events_timestamp'), table_name='scheduler_events')
    op.drop_index(op.f('ix_scheduler_events_pipeline_id'), table_name='scheduler_events')
    op.drop_index(op.f('ix_scheduler_events_created_by'), table_name='scheduler_events')
    op.drop_index(op.f('ix_scheduler_events_created_at'), table_name='scheduler_events')
    op.drop_index('idx_scheduler_pipeline_time', table_name='scheduler_events')
    op.drop_index('idx_scheduler_event_type_time', table_name='scheduler_events')
    op.drop_table('scheduler_events')
    op.drop_index(op.f('ix_pipeline_versions_pipeline_id'), table_name='pipeline_versions')
    op.drop_index(op.f('ix_pipeline_versions_created_by'), table_name='pipeline_versions')
    op.drop_index(op.f('ix_pipeline_versions_created_at'), table_name='pipeline_versions')
    op.drop_index('idx_version_published', table_name='pipeline_versions')
    op.drop_table('pipeline_versions')
    op.drop_index(op.f('ix_assets_deleted_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_by'), table_name='assets')
    op.drop_index(op.f('ix_assets_created_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_connection_id'), table_name='assets')
    op.drop_index('idx_asset_source_dest', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_pipelines_user_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_deleted_at'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_created_by'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_created_at'), table_name='pipelines')
    op.drop_index('idx_pipeline_schedule', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.drop_index(op.f('ix_connections_deleted_at'), table_name='connections')
    op.drop_index(op.f('ix_connections_created_by'), table_name='connections')
    op.drop_index(op.f('ix_connections_created_at'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_by'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alert_configs_user_id'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_name'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_enabled'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_deleted_at'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_created_by'), table_name='alert_configs')
    op.drop_index(op.f('ix_alert_configs_created_at'), table_name='alert_configs')
    op.drop_index('idx_alert_config_enabled', table_name='alert_configs')
    op.drop_table('alert_configs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
