"""add total_nodes to pipeline_runs

Revision ID: 852a25970efa
Revises: 4967bb507fdd
Create Date: 2025-12-25 06:37:48.286171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852a25970efa'
down_revision: Union[str, Sequence[str], None] = '4967bb507fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('pipeline_runs', sa.Column('total_nodes', sa.Integer(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE pipeline_runs SET total_nodes = 0")
    
    # Set as not nullable
    op.alter_column('pipeline_runs', 'total_nodes', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'total_nodes')
    # ### end Alembic commands ###
