"""add sample_data to step_runs

Revision ID: fac05ff95d44
Revises: 852a25970efa
Create Date: 2025-12-25 08:17:33.325762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac05ff95d44'
down_revision: Union[str, Sequence[str], None] = '852a25970efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_insights_final')
    op.drop_table('reporting_consolidated')
    op.add_column('step_runs', sa.Column('sample_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_runs', 'sample_data')
    op.create_table('reporting_consolidated',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.create_table('market_insights_final',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('global_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pipeline_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('pipeline_version_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('celery_task_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('retry_strategy', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_delay_seconds', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('infra_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('worker_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('queue_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
