"""Removed tenant-id support

Revision ID: V2
Revises: V1
Create Date: 2025-12-06 22:09:12.184139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V2'
down_revision: Union[str, Sequence[str], None] = 'V1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_backup')
    op.drop_table('users')
    op.drop_table('imported_users')
    op.drop_index(op.f('ix_alert_configs_tenant_id'), table_name='alert_configs')
    op.drop_constraint(op.f('uq_alert_config_name_per_tenant'), 'alert_configs', type_='unique')
    op.drop_column('alert_configs', 'tenant_id')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_column('alerts', 'tenant_id')
    op.drop_index(op.f('ix_asset_schema_versions_tenant_id'), table_name='asset_schema_versions')
    op.drop_column('asset_schema_versions', 'tenant_id')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('idx_asset_type_tenant'), table_name='assets')
    op.create_index('idx_asset_type_tenant', 'assets', ['asset_type'], unique=False)
    op.drop_column('assets', 'tenant_id')
    op.drop_index(op.f('idx_connection_health'), table_name='connections')
    op.drop_index(op.f('idx_connection_type_tenant'), table_name='connections')
    op.drop_index(op.f('ix_connections_tenant_id'), table_name='connections')
    op.drop_constraint(op.f('uq_connection_name_per_tenant'), 'connections', type_='unique')
    op.drop_column('connections', 'tenant_id')
    op.drop_index(op.f('ix_job_logs_tenant_id'), table_name='job_logs')
    op.drop_column('job_logs', 'tenant_id')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_column('jobs', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_edges_tenant_id'), table_name='pipeline_edges')
    op.drop_column('pipeline_edges', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_nodes_tenant_id'), table_name='pipeline_nodes')
    op.drop_column('pipeline_nodes', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_run_context_tenant_id'), table_name='pipeline_run_context')
    op.drop_column('pipeline_run_context', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_runs_tenant_id'), table_name='pipeline_runs')
    op.drop_column('pipeline_runs', 'tenant_id')
    op.drop_index(op.f('ix_pipeline_versions_tenant_id'), table_name='pipeline_versions')
    op.drop_column('pipeline_versions', 'tenant_id')
    op.drop_index(op.f('idx_pipeline_status_tenant'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_tenant_id'), table_name='pipelines')
    op.drop_constraint(op.f('uq_pipeline_name_per_tenant'), 'pipelines', type_='unique')
    op.create_foreign_key(None, 'pipelines', 'pipeline_versions', ['published_version_id'], ['id'], use_alter=True)
    op.drop_column('pipelines', 'tenant_id')
    op.drop_index(op.f('ix_scheduler_events_tenant_id'), table_name='scheduler_events')
    op.drop_column('scheduler_events', 'tenant_id')
    op.drop_index(op.f('ix_step_logs_tenant_id'), table_name='step_logs')
    op.drop_column('step_logs', 'tenant_id')
    op.drop_index(op.f('ix_step_runs_tenant_id'), table_name='step_runs')
    op.drop_column('step_runs', 'tenant_id')
    op.drop_index(op.f('ix_watermarks_tenant_id'), table_name='watermarks')
    op.drop_column('watermarks', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_watermarks_tenant_id'), 'watermarks', ['tenant_id'], unique=False)
    op.add_column('step_runs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_step_runs_tenant_id'), 'step_runs', ['tenant_id'], unique=False)
    op.add_column('step_logs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_step_logs_tenant_id'), 'step_logs', ['tenant_id'], unique=False)
    op.add_column('scheduler_events', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_scheduler_events_tenant_id'), 'scheduler_events', ['tenant_id'], unique=False)
    op.add_column('pipelines', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pipelines', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_pipeline_name_per_tenant'), 'pipelines', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipelines_tenant_id'), 'pipelines', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_pipeline_status_tenant'), 'pipelines', ['status', 'tenant_id'], unique=False)
    op.add_column('pipeline_versions', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pipeline_versions_tenant_id'), 'pipeline_versions', ['tenant_id'], unique=False)
    op.add_column('pipeline_runs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pipeline_runs_tenant_id'), 'pipeline_runs', ['tenant_id'], unique=False)
    op.add_column('pipeline_run_context', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pipeline_run_context_tenant_id'), 'pipeline_run_context', ['tenant_id'], unique=False)
    op.add_column('pipeline_nodes', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pipeline_nodes_tenant_id'), 'pipeline_nodes', ['tenant_id'], unique=False)
    op.add_column('pipeline_edges', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pipeline_edges_tenant_id'), 'pipeline_edges', ['tenant_id'], unique=False)
    op.add_column('jobs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.add_column('job_logs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_job_logs_tenant_id'), 'job_logs', ['tenant_id'], unique=False)
    op.add_column('connections', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_connection_name_per_tenant'), 'connections', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_connections_tenant_id'), 'connections', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_connection_type_tenant'), 'connections', ['connector_type', 'tenant_id'], unique=False)
    op.create_index(op.f('idx_connection_health'), 'connections', ['health_status', 'tenant_id'], unique=False)
    op.add_column('assets', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index('idx_asset_type_tenant', table_name='assets')
    op.create_index(op.f('idx_asset_type_tenant'), 'assets', ['asset_type', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.add_column('asset_schema_versions', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_asset_schema_versions_tenant_id'), 'asset_schema_versions', ['tenant_id'], unique=False)
    op.add_column('alerts', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.add_column('alert_configs', sa.Column('tenant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_alert_config_name_per_tenant'), 'alert_configs', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_alert_configs_tenant_id'), 'alert_configs', ['tenant_id'], unique=False)
    op.create_table('imported_users',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_table('users_backup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_backup_pkey'))
    )
    # ### end Alembic commands ###
