"""Removed tenant-id index


Revision ID: V3
Revises: V2
Create Date: 2025-12-07 00:07:08.383236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V3'
down_revision: Union[str, Sequence[str], None] = 'V2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_asset_type_tenant'), table_name='assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_asset_type_tenant'), 'assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###
